# Site settings
title: Woozy | Unite Against Germs
description: Woozy is a community-based flu and germ tracker. 
             Unite with others in your community to submit anonymous germ 
             reports that are collected in our state-of-the-art Invasion Station.
             
logo: logo.png

intro-title: Unite Against Germs
intro-blurb: At Woozy, we <strong>believe</strong> sharing germs online is better than sharing them in real-life. 
             With <strong>everyoneâ€™s contribution</strong>, we can slow the spread of germs in our <strong> families
             and communities</strong>.

report-title: Report
report-blurb: Submit an <strong>anonymous</strong> report to notify your <strong>community</strong> of germs in <strong>your area</strong>.
